# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UParking' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UParking

  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'UParkingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UParkingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
